title: Volkan Özen
author: Volkan
subtitle: personal webpage

url: https://volkanozen.github.io
baseurl: ""


footer_url: "https://volkanozen.github.io"
footer_text: "Volkan Özen – MfN Berlin"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "cv.pdf"
 - name: "Blog"
   link: "blog"
 
