title: Volkan Ozen
author: Volkan
subtitle: personal webpage

url: "https://volkanozen.github.io"
baseurl: ""


footer_url: "https://github.com/volkanozen"
footer_text: "Volkan Ozen – MfN"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Blog"
   link: "blog"
 
